name: deploy
on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout/@v1
      - uses: actions/setup-node/@v2
      - run: ls -la
      
  
      
