name: deploy
on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: git clone repo
        uses: actions/checkout/@1
        
      - name: build project
        run: cd wvmc-front && npm run-script build
      - name: lsla
        run: ls -la && ls -la wvmc-front && npm
  
      
  
      
