name: deploy
on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout/@v1
      - uses: actions/setup-node/@v2
      
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.anaxita }}" > "$HOME/.ssh/anaxita"
      - run: chmod 600 "$HOME/.ssh/anaxita"
      
      - run: npm-ci
      - run: npm run build
      
      - run: cd dist && rsync -e "ssh -i $HOME/.ssh/anaxita -o StrictHostKeyChecking=no" --archive --compress --delete --port=53344 programs@dc.kmsys.ru:/work

      
