name: prod-deploy-admins
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.18.0 ]
    env:
      REACT_APP_API_URL: http://172.19.11.25:8084
    steps:
      - uses: actions/checkout/@v2

      - uses: actions/setup-node/@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.anaxita }}" > "$HOME/.ssh/id_rsa"
      - run: chmod 600 "$HOME/.ssh/id_rsa"

      - run: npm ci
      - run: npm run-script build
        continue-on-error: true

      - run: cd build && scp -P 53344 -r -o "StrictHostKeyChecking no" . anaxita@bdc.kmsys.ru:/C:/Apache24/web/wvmc_prod_admins
      
      # - run: cd build && rsync -e "ssh -i $HOME/.ssh/anaxita -o StrictHostKeyChecking=no" --archive --compress --delete --port=53344 . anaxita@dc.kmsys.ru:C:\Apache24\web\wvmc-dev\
